name: Docker Compose CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-test:

    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest
        env:
          MONGO_INITDB_ROOT_USERNAME: mongouser
          MONGO_INITDB_ROOT_PASSWORD: mongopassword
        ports:
          - 27016:27017

    steps:
    - uses: actions/checkout@v3

    - name: Build and run Docker Compose
      run: |
        docker-compose -f docker-compose.yml up -d --build
    
    - name: Install Composer dependencies
      run: |
        docker exec invoice-api_app_1 composer install

    - name: Set up .env file
      run: |
        cp .env.example .env
        echo "DB_CONNECTION=mongodb" >> .env
        echo "DB_HOST=mongodb" >> .env
        echo "DB_PORT=27017" >> .env
        echo "DB_DATABASE=azapfy_database" >> .env
        echo "DB_USERNAME=mongouser" >> .env
        echo "DB_PASSWORD=mongopassword" >> .env
        echo "MAIL_MAILER=smtp" >> .env
        echo "MAIL_HOST=smtp.gmail.com" >> .env
        echo "MAIL_PORT=587" >> .env
        echo "MAIL_USERNAME=bioneandroid@gmail.com" >> .env
        echo "MAIL_PASSWORD=dsullcxewkdqafka" >> .env
        echo "MAIL_ENCRYPTION=tls" >> .env
        echo "MAIL_FROM_ADDRESS=bioneandroid@gmail.com" >> .env
        echo "MAIL_FROM_NAME="BioneAzza" >> .env

    - name: Generate JWT Secret
      run: |
        docker exec invoice-api_app_1 php artisan jwt:secret --force
    - name: Run tests or other commands
      run: |
       docker exec invoice-api_app_1 php artisan test
